config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :foods
  resources :healths
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    mount_uploader :image, ImagesUploader

    validates :title, presence: true
    validates :date, presence: true
end

app/models/health.rb
class Health < ApplicationRecord
    validates :body_weight, presence: true
    validates :condition, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  def index
    @foods = Food.all
  end

  # GET /foods/1
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to @food, notice: '正常に作成されました。'
    else
      render :new
    end
  end

  # PATCH/PUT /foods/1
  def update
    if @food.update(food_params)
      redirect_to @food, notice: '更新されました。'
    else
      render :edit
    end
  end

  # DELETE /foods/1
  def destroy
    @food.destroy
    redirect_to foods_url, notice: '削除しました。'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def food_params
      params.require(:food).permit(:image, :date, :title, :comment)
    end
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_health, only: [:show, :edit, :update, :destroy]

  # GET /healths
  def index
    @healths = Health.all
  end

  # GET /healths/1
  def show
  end

  # GET /healths/new
  def new
    @health = Health.new
  end

  # GET /healths/1/edit
  def edit
  end

  # POST /healths
  def create
    @health = Health.new(health_params)

    if @health.save
      redirect_to @health, notice: '正常に作成されました。'
    else
      render :new
    end
  end

  # PATCH/PUT /healths/1
  def update
    if @health.update(health_params)
      redirect_to @health, notice: '更新されました。'
    else
      render :edit
    end
  end

  # DELETE /healths/1
  def destroy
    @health.destroy
    redirect_to healths_url, notice: '削除されました。'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health
      @health = Health.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def health_params
      params.require(:health).permit(:date, :body_weight, :condition)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to healths_path if user_signed_in?
     end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  def create
    @schedule = Schedule.new(schedule_params)

    if @schedule.save
      redirect_to @schedule, notice: '正常に作成されました。'
    else
      render :new
    end
  end

  # PATCH/PUT /schedules/1
  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule, notice: '更新されました。'
    else
      render :edit
    end
  end

  # DELETE /schedules/1
  def destroy
    @schedule.destroy
    redirect_to schedules_url, notice: '削除されました。'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def schedule_params
      params.require(:schedule).permit(:name, :start_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bs4_bgcolor_for(flash_key)
        case flash_key
        when "success"
            "alert-success"
        when "error"
            "alert-danger"
        when "alert"
            "alert-warning"
        when "notice"
            "alert-info"
        else
            flash_key.to_s
        end
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= food.errors.count %> 件のエラーがあります</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to '詳細', @food ,class: "btn btn-outline-warning"%> |
<%= link_to '戻る', foods_path ,class: "btn btn-outline-danger"%>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>写真</th>
      <th>日付</th>
      <th>タイトル</th>
      <th>コメント</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @foods.each do |food| %>
    <tbody class="box">
      <tr>
        <td><img src="<%=food.image %>" style="wight:300px; height:200px;"></td>
        <td class="p400"><%= food.date %></td>
        <td class="p400"><%= food.title %></td>
        <td class="p400"><%= food.comment %></td>
        <td><%= link_to '詳細', food ,class: "btn btn-outline-warning btn-sm"%></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-outline-success btn-sm" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "btn btn-outline-danger btn-sm"%></td>
      </tr>
    </tbody>
  <% end %>
</table>
<br>

<%= link_to '新規作成', new_food_path ,class: "btn btn-outline-primary"%>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to '戻る', foods_path ,class: "btn btn-outline-danger"%>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class = big>写真:</strong>
  <%= image_tag @food.image_url if @food.image.present? %>
</p>

<p>
  <strong class = big>日付:</strong>
  <strong class = big><%= @food.date %></strong>
</p>

<p>
  <strong class = big>タイトル:</strong>
  <strong class = big><%= @food.title %></strong>
</p>

<p>
  <strong class = big>コメント:</strong>
  <strong class = big><%= @food.comment %></strong>
</p>

<%= link_to '編集', edit_food_path(@food) ,class: "btn btn-outline-success"%> |
<%= link_to '戻る', foods_path ,class: "btn btn-outline-danger"%>

app/views/healths/_form.html.erb
<%= form_with(model: health, local: true) do |form| %>
  <% if health.errors.any? %>
    <div id="error_explanation">
      <h2><%= health.errors.count %> 件のエラーがあります</h2>

      <ul>
      <% health.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :日付 %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :体重 %>
    <%= form.text_field :body_weight %>
  </div>

  <div class="field">
    <%= form.label :体調 %>
    <%= form.number_field :condition %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/healths/edit.html.erb
<h1>編集</h1>

<%= render 'form', health: @health %>

<%= link_to '詳細', @health ,class: "btn btn-outline-warning"%> |
<%= link_to '戻る', healths_path ,class: "btn btn-outline-danger"%>

app/views/healths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Healths</h1>

<%= line_chart Health.pluck(:date, :body_weight) %>

<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>体重</th>
      <th>体調</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @healths.each do |health| %>
  <tbody class="box">
      <tr class="space">
        <td class="p400"><%= health.date %></td>
        <td class="p400"><%= health.body_weight %></td>
        <td class="p400"><%= health.condition %></td>
        <td><%= link_to '詳細', health ,class: "btn btn-outline-warning btn-sm"%></td>
        <td><%= link_to '編集', edit_health_path(health) ,class: "btn btn-outline-success btn-sm"%></td>
        <td><%= link_to '削除', health, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "btn btn-outline-danger btn-sm"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_health_path ,class: "btn btn-outline-primary"%>

app/views/healths/new.html.erb
<h1>新規作成</h1>

<%= render 'form', health: @health %>

<%= link_to '戻る', healths_path ,class: "btn btn-outline-danger"%>

app/views/healths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class = big>日付:</strong>
  <strong class = big><%= @health.date %></strong>
</p>

<p>
  <strong class = big>体重:</strong>
  <strong class = big><%= @health.body_weight %></strong>
</p>

<p>
  <strong class = big>体調:</strong>
  <strong class = big><%= @health.condition %></strong>
</p>

<%= link_to '編集', edit_health_path(@health) ,class: "btn btn-outline-success"%> |
<%= link_to '戻る', healths_path ,class: "btn btn-outline-danger"%>

app/views/home/index.html.erb
<div class="top-wrapper">
      <div class="container">
        <h1>トップアスリートから健康を意識する全ての方へ</h1>
        <h1>Health<br>Management<br>App</h1>
      </div>
    </div>
    <div class="app-wrapper">
      <div class="container">
        <div class="heading">
          <h2>あなたをしっかりサポートします。</h2>
        </div>
        <div class="apps">
          <div class="app">
            <div class="app-icon">
              <%= image_tag 'health.jpg' %>
              <p>HEALTH</p>
            </div>
            <p class="text-contents">日々の体重変化を一眼で<br>確認できます。</p>
          </div>
          <div class="app">
            <div class="app-icon">
            <%= image_tag 'food.jpg' %>
              <p>FOOD</p>
            </div>
            <p class="text-contents">写真でその日の食事を<br>管理できます。</p>
          </div>
          <div class="app">
            <div class="app-icon">
            <%= image_tag 'schdule.jpg' %>
              <p>SCHDULE</p>
            </div>
            <p class="text-contents">忙しいあなたのスケジュールも<br>管理できます。</p>
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
    <div style="text-align:center">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/QsKKfJfVXL4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="message-wrapper">
      <div class="container">
        <div class="heading">
          <h2>強靭な体を手に入れませんか？</h2>
        </div>
        <span class="btn message"><%= link_to "登録して始める", new_user_registration_path %></span>
      </div>
    </div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="fixed-top mt-5 container">
      <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
        <%= value %>
        <button class="close" data-dismiss="alert">x</button>
      </div>
    </div>
  <% end %>
  

app/views/layouts/_footer.html.erb
<footer class="bg-light d-flex flex-column justify-content-end align-items-end">
  <div class="text-muted small px-3">Health Management App by Ruby on Rails & Bootstrap 4</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'HealthManagementApp', root_path, class: "navbar-brand" %>

  <div class="btn-group">
  <button>メニュー</button>
  <button type="button"
      class="btn btn-outline-dark dropdown-toggle dropdown-toggle-split"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <ul class="navbar-nav">
      <%  if user_signed_in?  %>
    <li class="nav-item">
      <%= link_to "Health", healths_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Food", foods_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Schedule", schedules_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
    <% else %> 
    <li class="nav-item">
      <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
    </li>
    <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <div id="modalArea"></div>
    <main>
      <div class="container-fruid h-100 p-2 d-flex flex-column">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= schedule.errors.count %> 件のエラーがあります</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :スケジュール %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :時間 %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to '詳細', @schedule ,class: "btn btn-outline-warning"%> |
<%= link_to '戻る', schedules_path ,class: "btn btn-outline-danger"%>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>スケジュール</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td class="p400"><%= schedule.name %></td>
        <td class="p400"><%= schedule.start_time %></td>
        <td><%= link_to '詳細', schedule ,class: "btn btn-outline-warning btn-sm"%></td>
        <td><%= link_to '編集', edit_schedule_path(schedule) ,class: "btn btn-outline-success btn-sm"%></td>
        <td><%= link_to '削除', schedule, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "btn btn-outline-danger btn-sm"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_schedule_path ,class: "btn btn-outline-primary"%>

<%= month_calendar events: @schedules do |date, schedules| %>
  <%= date %>

  <% schedules.each do |schedule| %>
    <div>
      <%= schedule.name %>
    </div>
  <% end %>
<% end %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to '戻る', schedules_path ,class: "btn btn-outline-danger"%>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class = big>スケジュール:</strong>
  <strong class = big><%= @schedule.name %></strong>
</p>

<p>
  <strong class = big>時間:</strong>
  <strong class = big><%= @schedule.start_time %></strong>
</p>

<%= link_to '編集', edit_schedule_path(@schedule) ,class: "btn btn-outline-success"%> |
<%= link_to '戻る', schedules_path ,class: "btn btn-outline-danger"%>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '←'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '→'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>